pipeline {
agent any

    environment {
        NGINX_HTML_DIR = "C:\\Program Files\\nginx-1.25.4\\html\\"
    }

    stages {
         stage('Install dependencies') {
            steps {
                // Run unit tests
                bat '''
                    cd react
                    npm install
                '''
            }
        }

        stage('Test') {
            steps {
                // Run unit tests
                bat '''
                    cd react
                    npm run test
                '''
            }
        }

         stage('Add .env file') {
            steps {
                // Run unit tests
                bat '''
                    cd react
                    (echo VITE_SOCKS_API_URL = http://localhost:3000/socks & echo VITE_ENVIRONMENT = development) > .env
                '''
            }
        }

        stage('Build') {
            steps {
                // Build for production
                bat '''
                    cd react
                    npm run build
                '''
            }
        }

        stage('Approval') {
            steps {
                input message: 'Approve for release?', submitter: 'user'
            }
        }

        stage('Deploy') {
            steps {
                // Deploy unit tested production build to nginx
                bat "xcopy react\\dist\\* \"${env.NGINX_HTML_DIR}\" /s /y"
            }
        }
    }
}